// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IsEmailRegisteredRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsEmailRegisteredRequest) Reset()         { *m = IsEmailRegisteredRequest{} }
func (m *IsEmailRegisteredRequest) String() string { return proto.CompactTextString(m) }
func (*IsEmailRegisteredRequest) ProtoMessage()    {}
func (*IsEmailRegisteredRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *IsEmailRegisteredRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsEmailRegisteredRequest.Unmarshal(m, b)
}
func (m *IsEmailRegisteredRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsEmailRegisteredRequest.Marshal(b, m, deterministic)
}
func (m *IsEmailRegisteredRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsEmailRegisteredRequest.Merge(m, src)
}
func (m *IsEmailRegisteredRequest) XXX_Size() int {
	return xxx_messageInfo_IsEmailRegisteredRequest.Size(m)
}
func (m *IsEmailRegisteredRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsEmailRegisteredRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsEmailRegisteredRequest proto.InternalMessageInfo

func (m *IsEmailRegisteredRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type IsEmailRegisteredReply struct {
	IsRegistered         bool     `protobuf:"varint,1,opt,name=isRegistered,proto3" json:"isRegistered,omitempty"`
	AccountUuid          string   `protobuf:"bytes,2,opt,name=accountUuid,proto3" json:"accountUuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsEmailRegisteredReply) Reset()         { *m = IsEmailRegisteredReply{} }
func (m *IsEmailRegisteredReply) String() string { return proto.CompactTextString(m) }
func (*IsEmailRegisteredReply) ProtoMessage()    {}
func (*IsEmailRegisteredReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *IsEmailRegisteredReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsEmailRegisteredReply.Unmarshal(m, b)
}
func (m *IsEmailRegisteredReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsEmailRegisteredReply.Marshal(b, m, deterministic)
}
func (m *IsEmailRegisteredReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsEmailRegisteredReply.Merge(m, src)
}
func (m *IsEmailRegisteredReply) XXX_Size() int {
	return xxx_messageInfo_IsEmailRegisteredReply.Size(m)
}
func (m *IsEmailRegisteredReply) XXX_DiscardUnknown() {
	xxx_messageInfo_IsEmailRegisteredReply.DiscardUnknown(m)
}

var xxx_messageInfo_IsEmailRegisteredReply proto.InternalMessageInfo

func (m *IsEmailRegisteredReply) GetIsRegistered() bool {
	if m != nil {
		return m.IsRegistered
	}
	return false
}

func (m *IsEmailRegisteredReply) GetAccountUuid() string {
	if m != nil {
		return m.AccountUuid
	}
	return ""
}

type GetInvitesRequest struct {
	AccountUuid          string   `protobuf:"bytes,1,opt,name=accountUuid,proto3" json:"accountUuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInvitesRequest) Reset()         { *m = GetInvitesRequest{} }
func (m *GetInvitesRequest) String() string { return proto.CompactTextString(m) }
func (*GetInvitesRequest) ProtoMessage()    {}
func (*GetInvitesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *GetInvitesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInvitesRequest.Unmarshal(m, b)
}
func (m *GetInvitesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInvitesRequest.Marshal(b, m, deterministic)
}
func (m *GetInvitesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInvitesRequest.Merge(m, src)
}
func (m *GetInvitesRequest) XXX_Size() int {
	return xxx_messageInfo_GetInvitesRequest.Size(m)
}
func (m *GetInvitesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInvitesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInvitesRequest proto.InternalMessageInfo

func (m *GetInvitesRequest) GetAccountUuid() string {
	if m != nil {
		return m.AccountUuid
	}
	return ""
}

type GetInvitesReply struct {
	InviteUuids          []string `protobuf:"bytes,1,rep,name=inviteUuids,proto3" json:"inviteUuids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInvitesReply) Reset()         { *m = GetInvitesReply{} }
func (m *GetInvitesReply) String() string { return proto.CompactTextString(m) }
func (*GetInvitesReply) ProtoMessage()    {}
func (*GetInvitesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *GetInvitesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInvitesReply.Unmarshal(m, b)
}
func (m *GetInvitesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInvitesReply.Marshal(b, m, deterministic)
}
func (m *GetInvitesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInvitesReply.Merge(m, src)
}
func (m *GetInvitesReply) XXX_Size() int {
	return xxx_messageInfo_GetInvitesReply.Size(m)
}
func (m *GetInvitesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInvitesReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetInvitesReply proto.InternalMessageInfo

func (m *GetInvitesReply) GetInviteUuids() []string {
	if m != nil {
		return m.InviteUuids
	}
	return nil
}

type RegisterRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReply) Reset()         { *m = RegisterReply{} }
func (m *RegisterReply) String() string { return proto.CompactTextString(m) }
func (*RegisterReply) ProtoMessage()    {}
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *RegisterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReply.Unmarshal(m, b)
}
func (m *RegisterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReply.Marshal(b, m, deterministic)
}
func (m *RegisterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReply.Merge(m, src)
}
func (m *RegisterReply) XXX_Size() int {
	return xxx_messageInfo_RegisterReply.Size(m)
}
func (m *RegisterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReply.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReply proto.InternalMessageInfo

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{6}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginReply struct {
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{7}
}

func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (m *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(m, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

func (m *LoginReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ActivateEmailRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateEmailRequest) Reset()         { *m = ActivateEmailRequest{} }
func (m *ActivateEmailRequest) String() string { return proto.CompactTextString(m) }
func (*ActivateEmailRequest) ProtoMessage()    {}
func (*ActivateEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{8}
}

func (m *ActivateEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateEmailRequest.Unmarshal(m, b)
}
func (m *ActivateEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateEmailRequest.Marshal(b, m, deterministic)
}
func (m *ActivateEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateEmailRequest.Merge(m, src)
}
func (m *ActivateEmailRequest) XXX_Size() int {
	return xxx_messageInfo_ActivateEmailRequest.Size(m)
}
func (m *ActivateEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateEmailRequest proto.InternalMessageInfo

func (m *ActivateEmailRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ActivateEmailReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateEmailReply) Reset()         { *m = ActivateEmailReply{} }
func (m *ActivateEmailReply) String() string { return proto.CompactTextString(m) }
func (*ActivateEmailReply) ProtoMessage()    {}
func (*ActivateEmailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{9}
}

func (m *ActivateEmailReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateEmailReply.Unmarshal(m, b)
}
func (m *ActivateEmailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateEmailReply.Marshal(b, m, deterministic)
}
func (m *ActivateEmailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateEmailReply.Merge(m, src)
}
func (m *ActivateEmailReply) XXX_Size() int {
	return xxx_messageInfo_ActivateEmailReply.Size(m)
}
func (m *ActivateEmailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateEmailReply.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateEmailReply proto.InternalMessageInfo

func (m *ActivateEmailReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type DropSingleTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropSingleTokenRequest) Reset()         { *m = DropSingleTokenRequest{} }
func (m *DropSingleTokenRequest) String() string { return proto.CompactTextString(m) }
func (*DropSingleTokenRequest) ProtoMessage()    {}
func (*DropSingleTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{10}
}

func (m *DropSingleTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropSingleTokenRequest.Unmarshal(m, b)
}
func (m *DropSingleTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropSingleTokenRequest.Marshal(b, m, deterministic)
}
func (m *DropSingleTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropSingleTokenRequest.Merge(m, src)
}
func (m *DropSingleTokenRequest) XXX_Size() int {
	return xxx_messageInfo_DropSingleTokenRequest.Size(m)
}
func (m *DropSingleTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DropSingleTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DropSingleTokenRequest proto.InternalMessageInfo

func (m *DropSingleTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DropSingleTokenReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropSingleTokenReply) Reset()         { *m = DropSingleTokenReply{} }
func (m *DropSingleTokenReply) String() string { return proto.CompactTextString(m) }
func (*DropSingleTokenReply) ProtoMessage()    {}
func (*DropSingleTokenReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{11}
}

func (m *DropSingleTokenReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropSingleTokenReply.Unmarshal(m, b)
}
func (m *DropSingleTokenReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropSingleTokenReply.Marshal(b, m, deterministic)
}
func (m *DropSingleTokenReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropSingleTokenReply.Merge(m, src)
}
func (m *DropSingleTokenReply) XXX_Size() int {
	return xxx_messageInfo_DropSingleTokenReply.Size(m)
}
func (m *DropSingleTokenReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DropSingleTokenReply.DiscardUnknown(m)
}

var xxx_messageInfo_DropSingleTokenReply proto.InternalMessageInfo

type DropAllTokensRequest struct {
	// A valid token of the account to drop all tokens of.
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropAllTokensRequest) Reset()         { *m = DropAllTokensRequest{} }
func (m *DropAllTokensRequest) String() string { return proto.CompactTextString(m) }
func (*DropAllTokensRequest) ProtoMessage()    {}
func (*DropAllTokensRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{12}
}

func (m *DropAllTokensRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropAllTokensRequest.Unmarshal(m, b)
}
func (m *DropAllTokensRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropAllTokensRequest.Marshal(b, m, deterministic)
}
func (m *DropAllTokensRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropAllTokensRequest.Merge(m, src)
}
func (m *DropAllTokensRequest) XXX_Size() int {
	return xxx_messageInfo_DropAllTokensRequest.Size(m)
}
func (m *DropAllTokensRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DropAllTokensRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DropAllTokensRequest proto.InternalMessageInfo

func (m *DropAllTokensRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DropAllTokensReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropAllTokensReply) Reset()         { *m = DropAllTokensReply{} }
func (m *DropAllTokensReply) String() string { return proto.CompactTextString(m) }
func (*DropAllTokensReply) ProtoMessage()    {}
func (*DropAllTokensReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{13}
}

func (m *DropAllTokensReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropAllTokensReply.Unmarshal(m, b)
}
func (m *DropAllTokensReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropAllTokensReply.Marshal(b, m, deterministic)
}
func (m *DropAllTokensReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropAllTokensReply.Merge(m, src)
}
func (m *DropAllTokensReply) XXX_Size() int {
	return xxx_messageInfo_DropAllTokensReply.Size(m)
}
func (m *DropAllTokensReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DropAllTokensReply.DiscardUnknown(m)
}

var xxx_messageInfo_DropAllTokensReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*IsEmailRegisteredRequest)(nil), "proto.IsEmailRegisteredRequest")
	proto.RegisterType((*IsEmailRegisteredReply)(nil), "proto.IsEmailRegisteredReply")
	proto.RegisterType((*GetInvitesRequest)(nil), "proto.GetInvitesRequest")
	proto.RegisterType((*GetInvitesReply)(nil), "proto.GetInvitesReply")
	proto.RegisterType((*RegisterRequest)(nil), "proto.RegisterRequest")
	proto.RegisterType((*RegisterReply)(nil), "proto.RegisterReply")
	proto.RegisterType((*LoginRequest)(nil), "proto.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "proto.LoginReply")
	proto.RegisterType((*ActivateEmailRequest)(nil), "proto.ActivateEmailRequest")
	proto.RegisterType((*ActivateEmailReply)(nil), "proto.ActivateEmailReply")
	proto.RegisterType((*DropSingleTokenRequest)(nil), "proto.DropSingleTokenRequest")
	proto.RegisterType((*DropSingleTokenReply)(nil), "proto.DropSingleTokenReply")
	proto.RegisterType((*DropAllTokensRequest)(nil), "proto.DropAllTokensRequest")
	proto.RegisterType((*DropAllTokensReply)(nil), "proto.DropAllTokensReply")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4f, 0xeb, 0xd3, 0x40,
	0x14, 0xfc, 0xc5, 0x12, 0xad, 0xaf, 0x2d, 0xa1, 0xcf, 0x10, 0x62, 0x8a, 0x18, 0xf6, 0xe4, 0xa1,
	0x04, 0xb5, 0x78, 0xf1, 0xd4, 0xa2, 0x22, 0x05, 0x41, 0x48, 0xed, 0x55, 0x88, 0xe9, 0xd2, 0x2e,
	0xc6, 0x24, 0x66, 0x37, 0x95, 0x7e, 0x77, 0x0f, 0xb2, 0xd9, 0x24, 0xcd, 0xbf, 0xf6, 0xe0, 0xa9,
	0xbc, 0x79, 0x33, 0xd3, 0x97, 0x9d, 0x01, 0x08, 0x72, 0x71, 0xf2, 0xd2, 0x2c, 0x11, 0x09, 0xea,
	0xc5, 0x0f, 0x79, 0x0d, 0xf6, 0x96, 0x7f, 0xfa, 0x15, 0xb0, 0xc8, 0xa7, 0x47, 0xc6, 0x05, 0xcd,
	0xe8, 0xc1, 0xa7, 0xbf, 0x73, 0xca, 0x05, 0x9a, 0xa0, 0x53, 0xb9, 0xb1, 0x35, 0x57, 0x7b, 0xf5,
	0xd4, 0x57, 0x03, 0xf9, 0x0e, 0xd6, 0x80, 0x22, 0x8d, 0x2e, 0x48, 0x60, 0xca, 0xf8, 0x15, 0x2c,
	0x64, 0x63, 0xbf, 0x85, 0xa1, 0x0b, 0x93, 0x20, 0x0c, 0x93, 0x3c, 0x16, 0xfb, 0x9c, 0x1d, 0xec,
	0x47, 0x85, 0x73, 0x13, 0x22, 0xef, 0x60, 0xfe, 0x99, 0x8a, 0x6d, 0x7c, 0x66, 0x82, 0xf2, 0xea,
	0x94, 0x8e, 0x4c, 0xeb, 0xcb, 0x56, 0x60, 0x34, 0x65, 0xf2, 0x1e, 0x17, 0x26, 0xac, 0x98, 0x25,
	0x81, 0xdb, 0x9a, 0x3b, 0x92, 0xa2, 0x06, 0x44, 0x3e, 0x80, 0x51, 0xdd, 0x76, 0xf7, 0xa3, 0xd1,
	0x81, 0x71, 0x1a, 0x70, 0xfe, 0x27, 0xc9, 0xaa, 0x9b, 0xeb, 0x99, 0x18, 0x30, 0xbb, 0x9a, 0xa4,
	0xd1, 0x85, 0xac, 0x61, 0xfa, 0x25, 0x39, 0xb2, 0xf8, 0xff, 0x2d, 0x09, 0x40, 0xe9, 0x20, 0xbf,
	0xc3, 0x04, 0x5d, 0x24, 0x3f, 0x69, 0x5c, 0xd2, 0xd4, 0x40, 0x96, 0x60, 0x6e, 0x42, 0xc1, 0xce,
	0x81, 0xa0, 0x65, 0x1a, 0xf5, 0xbf, 0x29, 0xb6, 0xd6, 0x64, 0x7b, 0x80, 0x1d, 0xb6, 0x74, 0xb6,
	0xe1, 0x09, 0xcf, 0xc3, 0x90, 0x72, 0x5e, 0x86, 0x55, 0x8d, 0xc4, 0x03, 0xeb, 0x63, 0x96, 0xa4,
	0x3b, 0x16, 0x1f, 0x23, 0xfa, 0x4d, 0x5a, 0xdc, 0xf7, 0xb7, 0xc0, 0xec, 0xf1, 0xe5, 0x5b, 0x2c,
	0x15, 0xbe, 0x89, 0xa2, 0x02, 0xe4, 0xf7, 0x5d, 0x4c, 0xc0, 0x0e, 0x3b, 0x8d, 0x2e, 0x6f, 0xff,
	0x8e, 0x60, 0xb2, 0xc9, 0xc5, 0x69, 0x47, 0xb3, 0x33, 0x0b, 0x29, 0xee, 0x61, 0xde, 0x6b, 0x20,
	0xbe, 0x54, 0xbd, 0xf6, 0x6e, 0xb5, 0xd9, 0x79, 0x71, 0x9b, 0x20, 0x0f, 0x7d, 0xc0, 0x35, 0xc0,
	0xb5, 0x41, 0x68, 0x97, 0xf4, 0x5e, 0x17, 0x1d, 0x6b, 0x60, 0xa3, 0x1c, 0xde, 0xc3, 0xb8, 0xb2,
	0xc5, 0x8a, 0xd5, 0xe9, 0x97, 0x63, 0xf6, 0x70, 0xa5, 0x7d, 0x03, 0x7a, 0x11, 0x39, 0x3e, 0x2b,
	0x09, 0xcd, 0x0a, 0x39, 0xf3, 0x36, 0xa8, 0x24, 0x5b, 0x98, 0xb5, 0x32, 0xc5, 0x45, 0xc9, 0x1a,
	0xea, 0x85, 0xf3, 0x7c, 0x78, 0xa9, 0xac, 0xbe, 0x82, 0xd1, 0x89, 0x0f, 0xab, 0xf7, 0x1a, 0xae,
	0x81, 0xb3, 0xb8, 0xb5, 0xae, 0x6f, 0x6b, 0x25, 0x89, 0x4d, 0x7e, 0xb7, 0x0d, 0xf5, 0x6d, 0xfd,
	0xf0, 0xc9, 0xc3, 0x8f, 0xc7, 0xc5, 0x6e, 0xf5, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x3e, 0xd2,
	0x95, 0xbe, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	IsEmailRegistered(ctx context.Context, in *IsEmailRegisteredRequest, opts ...grpc.CallOption) (*IsEmailRegisteredReply, error)
	GetInvites(ctx context.Context, in *GetInvitesRequest, opts ...grpc.CallOption) (*GetInvitesReply, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	ActivateEmail(ctx context.Context, in *ActivateEmailRequest, opts ...grpc.CallOption) (*ActivateEmailReply, error)
	// TODO: check token valid
	DropSingleToken(ctx context.Context, in *DropSingleTokenRequest, opts ...grpc.CallOption) (*DropSingleTokenReply, error)
	DropAllTokens(ctx context.Context, in *DropAllTokensRequest, opts ...grpc.CallOption) (*DropAllTokensReply, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) IsEmailRegistered(ctx context.Context, in *IsEmailRegisteredRequest, opts ...grpc.CallOption) (*IsEmailRegisteredReply, error) {
	out := new(IsEmailRegisteredReply)
	err := c.cc.Invoke(ctx, "/proto.AuthService/IsEmailRegistered", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetInvites(ctx context.Context, in *GetInvitesRequest, opts ...grpc.CallOption) (*GetInvitesReply, error) {
	out := new(GetInvitesReply)
	err := c.cc.Invoke(ctx, "/proto.AuthService/GetInvites", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error) {
	out := new(RegisterReply)
	err := c.cc.Invoke(ctx, "/proto.AuthService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, "/proto.AuthService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ActivateEmail(ctx context.Context, in *ActivateEmailRequest, opts ...grpc.CallOption) (*ActivateEmailReply, error) {
	out := new(ActivateEmailReply)
	err := c.cc.Invoke(ctx, "/proto.AuthService/ActivateEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) DropSingleToken(ctx context.Context, in *DropSingleTokenRequest, opts ...grpc.CallOption) (*DropSingleTokenReply, error) {
	out := new(DropSingleTokenReply)
	err := c.cc.Invoke(ctx, "/proto.AuthService/DropSingleToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) DropAllTokens(ctx context.Context, in *DropAllTokensRequest, opts ...grpc.CallOption) (*DropAllTokensReply, error) {
	out := new(DropAllTokensReply)
	err := c.cc.Invoke(ctx, "/proto.AuthService/DropAllTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	IsEmailRegistered(context.Context, *IsEmailRegisteredRequest) (*IsEmailRegisteredReply, error)
	GetInvites(context.Context, *GetInvitesRequest) (*GetInvitesReply, error)
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	ActivateEmail(context.Context, *ActivateEmailRequest) (*ActivateEmailReply, error)
	// TODO: check token valid
	DropSingleToken(context.Context, *DropSingleTokenRequest) (*DropSingleTokenReply, error)
	DropAllTokens(context.Context, *DropAllTokensRequest) (*DropAllTokensReply, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) IsEmailRegistered(ctx context.Context, req *IsEmailRegisteredRequest) (*IsEmailRegisteredReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsEmailRegistered not implemented")
}
func (*UnimplementedAuthServiceServer) GetInvites(ctx context.Context, req *GetInvitesRequest) (*GetInvitesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInvites not implemented")
}
func (*UnimplementedAuthServiceServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedAuthServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthServiceServer) ActivateEmail(ctx context.Context, req *ActivateEmailRequest) (*ActivateEmailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateEmail not implemented")
}
func (*UnimplementedAuthServiceServer) DropSingleToken(ctx context.Context, req *DropSingleTokenRequest) (*DropSingleTokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropSingleToken not implemented")
}
func (*UnimplementedAuthServiceServer) DropAllTokens(ctx context.Context, req *DropAllTokensRequest) (*DropAllTokensReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropAllTokens not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_IsEmailRegistered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsEmailRegisteredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).IsEmailRegistered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/IsEmailRegistered",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).IsEmailRegistered(ctx, req.(*IsEmailRegisteredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetInvites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInvitesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetInvites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/GetInvites",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetInvites(ctx, req.(*GetInvitesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ActivateEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ActivateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/ActivateEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ActivateEmail(ctx, req.(*ActivateEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_DropSingleToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropSingleTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).DropSingleToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/DropSingleToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).DropSingleToken(ctx, req.(*DropSingleTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_DropAllTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropAllTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).DropAllTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/DropAllTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).DropAllTokens(ctx, req.(*DropAllTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsEmailRegistered",
			Handler:    _AuthService_IsEmailRegistered_Handler,
		},
		{
			MethodName: "GetInvites",
			Handler:    _AuthService_GetInvites_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _AuthService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "ActivateEmail",
			Handler:    _AuthService_ActivateEmail_Handler,
		},
		{
			MethodName: "DropSingleToken",
			Handler:    _AuthService_DropSingleToken_Handler,
		},
		{
			MethodName: "DropAllTokens",
			Handler:    _AuthService_DropAllTokens_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
